# Generated by Django 5.0.14 on 2026-04-28 17:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccuracyTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('question', models.TextField(max_length=1023)),
                ('expected_answer', models.TextField(max_length=4095)),
                ('required_terms', models.TextField(blank=True, max_length=1023)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccuracyTestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_answer', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('missing_terms', models.TextField(blank=True, max_length=1023)),
                ('response_time_ms', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('review', 'Needs Review'), ('error', 'Error')], default='review', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='developer.accuracytestcase')),
            ],
        ),
        migrations.CreateModel(
            name='DatabaseFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=1023)),
                ('file', models.FileField(blank=True, upload_to='rag_dataset')),
                ('source_type', models.CharField(choices=[('file', 'File Upload'), ('text', 'Text Upload')], default='file', max_length=10)),
                ('gcs_uri', models.CharField(blank=True, max_length=1024)),
                ('rag_resource_name', models.CharField(blank=True, max_length=1024)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date added')),
                ('uploader', models.ForeignKey(blank=True, on_delete=models.SET(None), to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('response_time_ms', models.IntegerField()),
                ('success', models.BooleanField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
