# Generated by Django 5.0.14 on 2026-04-28 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccuracyTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('question', models.TextField(max_length=1023)),
                ('expected_answer', models.TextField(max_length=4095)),
                ('required_terms', models.TextField(blank=True, max_length=1023)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccuracyTestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_answer', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('missing_terms', models.TextField(blank=True, max_length=1023)),
                ('response_time_ms', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('review', 'Needs Review'), ('error', 'Error')], default='review', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='developer.accuracytestcase')),
            ],
        ),
    ]
